### PR TITLE
[WIP]: No large binaries/files in cookbooks!

### PR DESCRIPTION
**Pull request by jjasghar**
- This is the intial commit to check to make sure you are not shipping gems with your cookbooks

- No gems were harmed in the writing of this PR.

### CODE REVIEW

**Comment by coderanger** [comment]
This seems oddly specific? Is this a common problem I'm not aware of?

**Comment by doubt72** [comment]
Needs more cowbell.

**Comment by jjasghar** [comment]
@coderanger Actually yes. In my travels with chef i've seen people try to ship gems with cookbooks. To be honest, this could any real executable; but we should start with gems.

**Comment by coderanger** [comment]
Why would shipping a gem with a `cookbook_file` be wrong? Or at least any more wrong than any other type of package.

**Comment by jjasghar** [comment]
I've seen people try to ship gems in `files/default` and wonder why syncs would take a long time. Ideally you'd have your gems in a shared location and the code would pull it down.

**Comment by coderanger** [comment]
Sure, but that's at best a "best practice" not a lint check. And there are lots of good reasons to do it, just like there are reasons to ship debs and RPMs in a cookbook sometimes.

**Comment by coderanger** [comment]
If you wanted to make a general check for this "best practice" it should probably be based on file size anyway, not extension.

**Comment by tas50** [comment]
This should really be generalized to "don't ship large files in your cookbook" and we can decide on some large file size we think is evil (1 meg or so).  I've seen tons of people ship debs/wars/rpms in their cookbooks.  It is something we should discourage, but in a more general way.

**Comment by coderanger** [comment]
Yeah, I would support either a per-file or total size threshold (or maybe both?) a lot more than this. This check feels like it would just leave a user confused.

**Comment by cheeseplus** [comment]
Also shipping gems is totally a cool thing to do like for network devices where that is the best delivery mechanism.

**Comment by jjasghar** [comment]
Having a check for a binary over a meg seems more reasonable. Not sure how to make this happen, but maybe that's more the spirit of what I'm trying to do here.

**Comment by xenolinguist** [comment]
:+1: to changing this to a file size check.

**Comment by jjasghar** [comment]
So if we move this to a file size check; do we have an idea "where the chef server starts erroring" at too big of a binary?

**Comment by tas50** [comment]
It's not that we're breaking the Chef server we're just mis-using Chef, which is a perfectly acceptable thing to alert on in Foodcritic.  The Chef server is not an artifact store for releasing your application. That should be done in S3 or Artifactory/Nexus.  I think setting a 1meg limit is perfectly reasonable and if people really want to keep pushing binaries in their cookbooks they can always turn it off.

**Comment by cheeseplus** [comment]
+1 to @tas50 point - I just didn't like us singling out gems as those are, in my exp, the most valid (ab)use

**Comment by coderanger** [comment]
1M per file and 10M overall cookbook size seem like a reasonable place to start for a linter. If we had RubyCop-ish levels it might be nice to have both warning and error thresholds but alas :)

**Comment by cheeseplus** [comment]
:+1:

**Comment by jjasghar** [comment]
Awesome, so obviously this PR (code) is completely wrong now. Any chance I can ask some pairing time with someone to make this happen? I'm betting we could get this done in under an hour.

**Comment by cheeseplus** [comment]
@jjasghar no foodcritic experience but I'd be up for pairing

**Comment by tas50** [comment]
@jjasghar I'm going to close this out since the no large binaries check would be an entirely different thing.

**Pull request closed without merging**
