### PR TITLE
Add metadata for missing chef 11 versions

### PR DESCRIPTION
**Pull request by jdmundrawala**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:  i imagine we need this for chef-12.0.x as well.

**Comment by lamont-granquist** [comment]
paging @jaymzh

**Comment by jdmundrawala** [comment]
@lamont-granquist i think chef 12 is going to require some work. It looked like switching to ruby 2 produced a lot of warnings when running the generate task. Will look into it more when I get a chance.

**Comment by btm** [comment]
this looks sadly manual. :(

@acrmp I guess this is the right thing to do?

**Comment by acrmp** [comment]
@btm What looks manual? If the generation can be made to work on Chef 12 then that would be the best way forward.

**Comment by david-crowder** [comment]
Is there anything I can do to help with this issue? It seems like all of the comments specific to chef 11 have been addressed. Though 11.18.x seems to have come out since this PR was made. 
I have an interest in this because I use foodcritic and I have started to use the sensitive attribute in cookbooks, which sadly the current release of foodcritic does not support.

**Comment by lamont-granquist** [comment]
mergifying

**Comment by btm** [comment]
@acrmp I guess I was surprised we've got to run something and ship a release for this (and should be doing so regularly).

**Comment by jdmundrawala** [comment]
@btm i think we should build the artifacts foodcritic needs as part of the chef client build

**Pull request merged**
