### PR TITLE
Remove Chef 11 metadata and rule support

### PR DESCRIPTION
**Pull request by tas50**
Removes Chef 11 metadata from Foodcritic and cuts the binary size in 1/2. We released Chef 12 about 18 months ago. It's time to start moving tools on to support 12+

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:-1: until you find another 4 lines to delete

**Comment by tas50** [comment]
I tried, but that's all I can find. Sorry @lamont-granquist

**Comment by tas50** [comment]
Found 4 more for you @lamont-granquist

**Comment by lamont-granquist** [comment]
beautiful 👍

**Pull request merged**
