### PR TITLE
Lcg/changelog updates

### PR DESCRIPTION
**Pull request by lamont-granquist**
CHANGELOG entries for unreleased code to date.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@acrmp @jaymzh @fnichol review?

**Comment by jaymzh** [comment]
This conflicts with #302

**Comment by lamont-granquist** [comment]
didn't see that had changelog as well.  i just merged his text into mine.

**Comment by lamont-granquist** [comment]
ah i see, the @'s dont actually work on github markdown, bummer...

**Pull request merged**
