### PR TITLE
Add windows_package.success_codes attributes

### PR DESCRIPTION
**Pull request by Annih**
This PR add `success_codes`  to `windows_package` recognized attributes list.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Can't accept this.

These files are autogenerated via extracting properties off of resources in the core chef DSL.  If you manually patch them they'll get destroyed when these files are regenerated, and you'll lose it on every upgrade.

This property exists only on the windows_package resource which is in the cookbook and not in core chef.  The proper solution to this problem is to finally port all of the functionality of windows_package  in the cookbook into core chef, and to nuke the resource from the cookbook.  

Until then you'll need to continue to tag it manually in the cookbooks you're writing.

**Comment by tas50** [comment]
Just a small side note: Adding the resources from the Windows cookbook into core is on the roadmap so the need for this also goes away in the next few quarters.

**Comment by lamont-granquist** [comment]
s/next few quarters/next quarter/ according to btm on the linked to ticket.

**Comment by Annih** [comment]
Nice, thanks for the explaination :)

**Pull request closed without merging**
