### PR TITLE
Require the latest rubocop

### PR DESCRIPTION
**Pull request by tas50**
If someone is doing dev work we should ensure they have a modern release

### CODE REVIEW

**Comment by lamont-granquist** [comment]
currently i think this is pointless and we don't rubocop anything, and i'd vastly prefer to use finstyle over rubocop...

**Comment by lamont-granquist** [comment]
also '~> 0.20' still matches '0.38.0' or whatever

my Gemfile.lock has this:

```
% egrep rubocop Gemfile.lock
    rubocop (0.35.1)
  rubocop (~> 0.20)
```

**Comment by tas50** [comment]
we should get something in there and start enforcing via travis.  At the moment this does nothing, but bumping to to .35 ensured you had a recent release.  Let me get an actual ruleset and get this in travis first.

**Comment by lamont-granquist** [comment]
doesn't really 'ensure', though, people still need to 'bundle update' correctly or their lockfiles will be out of date, a fresh bundle install will pull the latest.

**Pull request closed without merging**
